### ISSUE TITLE
validateMnemonic() returns TRUE when it should not

### ISSUE THREAD

**Issue by Overtorment** [bitcoinjs/electrum-mnemonic#2]
I'm still digging into this issue, but the following text produced TRUE 

` extpubkey zpub6rizchhnrwzhhz3z4dhcjmesgyafmmzbrc9txhnidr313xjbcv4kidubderkhhl7rmsqacyd82fq38e4whgs8dg7cpsxx3dsgwayxseerf4 masterfingerprint 7d2f0272 accountkeypath 84 0 0 cobovaultfirmwareversi
on 2 6 1 btc only `

full code that produced it:

```
const mn = require('electrum-mnemonic');
```

```js
  validateMnemonic() {
    console.warn('this.secret =', "`" + this.secret + "`");
    const valid = mn.validateMnemonic(this.secret, PREFIX);
    console.warn({valid, PREFIX});
    return valid;
  }
```

console output:

```
    this.secret = ` extpubkey zpub6rizchhnrwzhhz3z4dhcjmesgyafmmzbrc9txhnidr313xjbcv4kidubderkhhl7rmsqacyd82fq38e4whgs8dg7cpsxx3dsgwayxseerf4 masterfingerprint 7d2f0272 accountkeypath 84 0 0 cobovaultfirmwareversi
on 2 6 1 btc only `

    { valid: true, PREFIX: '01' }
```

**Comment by Overtorment** [comment]
PS. ver 2.0.0

**Comment by junderw** [comment]
Yes. This is how electrum mnemonics work.

https://github.com/spesmilo/electrum/blob/9c1a51547a301e765b9b0f9935c6d940bb9d658e/electrum/mnemonic.py#L225-L228

You can enter that string into Electrum and it will restore a wallet for you.

**Comment by junderw** [comment]
You can enter random keyboard keys into seed for Electrum and if the hash matches one of the prefixes (1 in 256 chance to match 01)

ie: `3y5y3n1wmeo0` generates wallet with first address `1GRLZx5xMk8MW7JiYBMG8Abnr3gusQszPS`

![スクリーンショット_2021-05-14_07-44-38](https://user-images.githubusercontent.com/11246316/118196690-64863100-b488-11eb-9197-1a6bea279e10.png)
![スクリーンショット_2021-05-14_07-45-16](https://user-images.githubusercontent.com/11246316/118196702-694ae500-b488-11eb-93cb-d3e7f42c5b8e.png)

**Comment by junderw** [comment]
seed 2ep4wzpqd2xw
first address bc1qy5pxduptmnhkq3h5fnt5myj5fcwuhvnl97fzl7
![スクリーンショット_2021-05-14_07-47-19](https://user-images.githubusercontent.com/11246316/118196897-c0e95080-b488-11eb-95c4-620461bfde98.png)
![スクリーンショット_2021-05-14_07-47-44](https://user-images.githubusercontent.com/11246316/118196905-c3e44100-b488-11eb-9577-b78211ea0d54.png)
